### PR TITLE
add Git Updater integration

### LINKED ISSUE #77: Add support for Git-updater for testing
For testing it would be helpful to add full support when using Git-updater, so its easy to get the latest code from any bransch when testing in WordPress.

In the aspire-update.php file add some headers:
GitHub Plugin URI: https://github.com/aspirepress/aspireupdate
Primary Branch: main

Docs:  https://git-updater.com/knowledge-base/required-headers/

### PR DESCRIPTION
**Pull request by afragen**
# Pull Request

## What changed?

Added appropriate headers for Git Updater integration.

Fixes #77 

## CERTIFICATION

By opening this pull request, I do agree to abide by
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time
of my contribution as proven by the
revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the
version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person
or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree
that this code may be licensed under any license deemed appropraite by AspirePress, including but not
limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my
rights or my copyright to this code.

### CODE REVIEW

**Review by namithj — APPROVED** [review]

**Comment by asirota** [comment]
@sarah-savage please have a look.

**Comment by asirota** [comment]
Can I get an explanation on why the plugin requires this header?

**Comment by namithj** [comment]
It's for git updater integration. To pull updates directly from popular Git platforms for those who use the git updater plugin.

**Comment by asirota** [comment]
Ok but why does our plugin need this?

**Comment by asirota** [comment]
Also there is no issue on this for discussion. @afragen please add an issue first before we do a PR. That's our usual workflow.

**Review by asirota — CHANGES_REQUESTED** [review]
there is issue #77

**Comment by afragen** [comment]
> Also there is no issue on this for discussion. @afragen please add an issue first before we do a PR. That's our usual workflow.

The issue is #77

**Comment by ipajen** [comment]
@asirota is for QA. See ticket 
https://github.com/aspirepress/AspireUpdate/issues/77

the new headers is so Git updater knows where to download the code on GitHub. It saves time for testing as get the latest code and easy to change branch if needed. Been using it for years when testing other plugins.

**Comment by asirota** [comment]
Sorry how is this relevant for QA. Please inform me how this helps QA.

**Comment by ipajen** [comment]
> Please inform me how this helps QA. Tell me like I'm 5.

It saves time. QA can get latest AP code from GitHub.with one click on any Wordpress test installation  when using the git updater plugin instead of manually doing it.  By adding the headers in AP the git updater will know where to find the AP GitHub code.The headers does not affect AP at all.

**Comment by asirota** [comment]
Gotcha. Seems innocuous. It's basically a testing tool. Is this something we want to have in our code for production branches or just test branches ?

**Comment by ipajen** [comment]
> Gotcha. Seems innocuous. It's basically a testing tool. Is this something we want to have in our code for production branches or just test branches ?

I say production. It’s totally harmless as there is no dependencies to any code. It will be of benefit for other people who want to test the AP code. You should try it out when ever you have a chance as it’s a great tool.

**Comment by afragen** [comment]
It should be in all branches. This will allow the user to switch between the branches for testing, etc.

**Comment by afragen** [comment]
@asirota how will the plugin currently get updates? Git Updater integration can provide that.

**Comment by asirota** [comment]
It will get updates from AspireCloud.

**Comment by afragen** [comment]
The default action for Git Updater is to update the primary branch from dot org, or in this case, AspireCloud, which replaces dot org.

This allows for any development branches of the plugin to update directly from the git host.

**Review by asirota — COMMENTED** [review]
For now this PR is open for comments.

**Comment by ipajen** [comment]
@costdev Do you have any feedback on this PR? 🙏

**Comment by costdev** [comment]
Thanks for the ping @ipajen!

Certainly one of the major issues that software projects face is getting enough testers. This would enable those with GitUpdater to easily switch branch to the bleeding edge of the plugin and should help increase the number of bug reports/enhancement requests as use cases arise.

**Review by asirota — APPROVED** [review]

**Pull request merged**
