### PR TITLE
update afragen/translations-updater with error caching/logging

### PR DESCRIPTION
**Pull request by afragen**
Added API error caching for 60 min as GitHub API rate limits unauthenticated requests for 60 requests/hour. Leaves an entry in the debug.log

### CODE REVIEW

**Comment by afragen** [comment]
Fixes #200

**Comment by afragen** [comment]
Hopefully fixes #188

**Comment by ipajen** [comment]
@afragen 

the https://github.com/aspirepress/aspireupdate/issues/188 issue is solved in the fix.

But i am getting follow PHP warning when the 403 kicks in on language-pack.json

``Undefined property: stdClass::$name `
```
`wp-content/plugins/aspireupdate/vendor/afragen/translations-updater/src/Translations_Updater/API.php:141
Fragen\Translations_Updater\Language_Pack_API->api()
wp-content/plugins/aspireupdate/vendor/afragen/translations-updater/src/Translations_Updater/Language_Pack_API.php:87
Fragen\Translations_Updater\Language_Pack_API->get_language_pack_json()
wp-content/plugins/aspireupdate/vendor/afragen/translations-updater/src/Translations_Updater/Language_Pack_API.php:56
Fragen\Translations_Updater\Language_Pack_API->get_language_pack()
wp-content/plugins/aspireupdate/vendor/afragen/translations-updater/src/Translations_Updater/Language_Pack.php:62
Fragen\Translations_Updater\Language_Pack->run()
wp-content/plugins/aspireupdate/vendor/afragen/translations-updater/src/Translations_Updater/Base.php:52
Fragen\Translations_Updater\Init->get_remote_repo_data()
wp-content/plugins/aspireupdate/vendor/afragen/translations-updater/src/Translations_Updater/Init.php:78
Fragen\Translations_Updater\Init->run()
wp-content/plugins/aspireupdate/aspire-update.php:76
aspireupdate_init_translations()
wp-includes/class-wp-hook.php:324
do_action('init')
wp-settings.php:704`
```

**Comment by afragen** [comment]
Well maybe it not quite the fix.

**Comment by afragen** [comment]
I'm thinking it might be better to return a WP_Error for a validation failure.

**Comment by ipajen** [comment]
Getting two PHP warnings now when 403 comes.

`Undefined property: stdClass::$name | +wp-content/plugins/aspireupdate/vendor/afragen/translations-updater/src/Translations_Updater/API.php:141`


`Undefined property: WP_Error::$slug | +wp-content/plugins/aspireupdate/vendor/afragen/translations-updater/src/Translations_Updater/Language_Pack.php:63
`

**Comment by ipajen** [comment]
But i see also in the debug logs

`[17-Nov-2024 17:41:43 UTC] Translations Updater Error:  (aspireupdate:main) - API rate limit exceeded for XXXIP. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

**Comment by afragen** [comment]
Is this with current change back to returning false?

https://github.com/afragen/aspireupdate/commit/7c4774e93cd65e4300a568296d86c87c374b6296

**Review by asirota — APPROVED** [review]

**Comment by afragen** [comment]
Just finished an update to the error handling. It should now degrade gracefully and document API timeout errors in the error log.

**Comment by ipajen** [comment]
Tested on the https://github.com/afragen/aspireupdate/tree/error-cache-logging bransch and the PHP warnings are gone and it’s caching if the rate limit is hit so it will not pound the GitHub API.

**Review by ipajen — APPROVED** [review]

**Pull request merged**
