### PR TITLE
Voltron has landed.

### PR DESCRIPTION
**Pull request by namithj**
Easter Egg Ascii Art

# Pull Request

## What changed?

Easter Egg Ascii Art for our Settings Page

## Why did it change?

Easter Egg Ascii Art for our Settings Page

## Did you fix any specific issues?

Just for fun

## CERTIFICATION

By opening this pull request, I do agree to abide by
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time
of my contribution as proven by the
revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the
version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person
or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree
that this code may be licensed under any license deemed appropraite by AspirePress, including but not
limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my
rights or my copyright to this code.

### CODE REVIEW

**Comment by costdev** [comment]
What is going on? :joy:

**Comment by namithj** [comment]
Voltron has landed.

**Comment by asirota** [comment]
@namithj when is this triggered exactly? On a Settings Reset?

**Comment by namithj** [comment]
Its at the bottom of the settings page, not visible until the text is selected.

**Comment by costdev** [comment]
Serious products everyone :joy:

**Comment by asirota** [comment]
> Serious products everyone 😂 I'll go with consensus though 😉

Aww come on we can have some fun can't we?

**Comment by asirota** [comment]
voltron
voltron

PNG and SVG for your fun.. Maybe a click on ascii art makes it colourful?

**Comment by namithj** [comment]
> voltron voltron
> 
> PNG and SVG for your fun.. Maybe a click on ascii art makes it colourful?

Coming up for Phase 2.

**Comment by asirota** [comment]
That's easy with https://www.ascii-art-generator.org/

[voltron.zip](https://github.com/user-attachments/files/17619468/voltron.zip)

**Review by asirota — APPROVED** [review]

**Pull request merged**
