### PR TITLE
Translations loading fix112

### PR DESCRIPTION
**Pull request by sebastienserre**
# Pull Request
 fix issue https://github.com/aspirepress/AspireUpdate/issues/112

## What changed?
I have added a function to load the textdomain and make the  translations working

## Did you fix any specific issues?

fix issue https://github.com/aspirepress/AspireUpdate/issues/112

## CERTIFICATION

By opening this pull request, I do agree to abide by
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time
of my contribution as proven by the
revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the
version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person
or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree
that this code may be licensed under any license deemed appropraite by AspirePress, including but not
limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my
rights or my copyright to this code.

### CODE REVIEW

**Comment by sebastienserre** [comment]
@namithj , I didn't find how to add you as reviewer.

**Comment by namithj** [comment]
@asirota should we actually do this.  The languages loading is automatic in Wordpress (not sure from which version), this can serve for older versions though, no harm in adding it.  Only problem I see is, people might not fully follow the naming conventions required for autoloading.

**Comment by asirota** [comment]
Well done. Thank you @sebastienserre for making AspireUpdate load translations that we get submitted. Eventually we will use something like glotpress but for now they will be part of the plugin.

**Comment by afragen** [comment]
> @asirota should we actually do this. The languages loading is automatic in Wordpress (not sure from which version), this can serve for older versions though, no harm in adding it. Only problem I see is, people might not fully follow the naming conventions required for autoloading.

Since WP 4.6 it should be unnecessary to use `load_plugin_textdomain()`

**Comment by asirota** [comment]
> Since WP 4.6 it should be unnecessary to use `load_plugin_textdomain()`

Is there a better approach we can use?

**Comment by namithj** [comment]
It should have been unnecessary, but apparently the translations are not loading without it.  This was the original prescribed method so nothing wrong in having it there.

**Comment by afragen** [comment]
So yes, as of WP 4.6 translation files that are stored in the `WP_LANG_DIR/plugins` or `WP_LANG_DIR/themes`. Files stored within the plugin's languages folder I believe it's still required to use `load_plugin_textdomain()` which should be loaded in the `init` hook.

There are a few methods of decoupled language packs that load the translation files into the `WP_LANG_DIR/plugins` and therefore are automatically loaded.

https://github.com/wearerequired/traduttore
https://github.com/afragen/translations-updater

I think both of the above will update languages packs separately from the plugin and load the packs into the WP_LANG_DIR/plugins folder.

**Comment by sebastienserre** [comment]
On my side, the French translation was correctly loaded in the plugin list (plugin description) without the `load_plugin_textdomain()`.
Only plugin settings were not correctly loaded which is maybe the sign of a bug inside the plugin.

**Pull request merged**
