### PR TITLE
Add French Translation

### PR DESCRIPTION
**Pull request by sebastienserre**
# Pull Request
French Answer to the call https://github.com/aspirepress/AspireUpdate/issues/75 

## What changed?

1. Create a `/languages/`
2. Create a `.pot` file
3. Create the French `fr_FR` translation

## Why did it change?

AspireUpdate is now available in 1 other locale than `en_US` !
## Did you fix any specific issues?

(Please tag any specific issues here...)

## CERTIFICATION

By opening this pull request, I do agree to abide by
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time
of my contribution as proven by the
revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the
version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person
or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree
that this code may be licensed under any license deemed appropraite by AspirePress, including but not
limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my
rights or my copyright to this code.

### CODE REVIEW

**Comment by namithj** [comment]
Can you tag me for review, I am not getting the option to review after self assigning.

**Review by namithj — APPROVED** [review]

**Comment by ipajen** [comment]
I don’t know France but just wondering.

#. URI of the plugin
msgid "https://aspirepress.org/"
msgstr "AspireUpdate"

Shouldn’t the msgstr be the URL?

**Comment by asirota** [comment]
@sebastienserre see above from @ipajen

**Comment by sebastienserre** [comment]
Fixed by https://github.com/aspirepress/AspireUpdate/pull/113

**Pull request merged**
