### PR TITLE
pull in most recent changes on main into playground-ready

### PR DESCRIPTION
**Pull request by asirota**
# Pull Request

## What changed?

changes on main being pulled into playground-ready

## Why did it change?

normal course of actions

## Did you fix any specific issues?

I think eventually this could be a process that is automated with resolve conflicts to be set as exceptions for continuous integration and  deployment

## CERTIFICATION

By opening this pull request, I do agree to abide by
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time
of my contribution as proven by the
revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the
version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person
or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree
that this code may be licensed under any license deemed appropraite by AspirePress, including but not
limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my
rights or my copyright to this code.

### CODE REVIEW

**Comment by asirota** [comment]
What do you all think about automatically merging PRs into playground-ready from main when requested? Or should a review still be done? I was thinking of automating this to be done say nightly.

**Comment by namithj** [comment]
If everyone is testing on playground then let's auto merge.  My preference is someone giving it a spin locally before releasing it to testers.

**Comment by costdev** [comment]
Yeah I think every PR should be reviewed and also given a spin (with `gh pr checkout <number>`) before a PR is approved. That means it should be ready for wider testing via playground. By following that, an automated merge to the playground-ready branch should be pretty safe.

**Comment by asirota** [comment]
There is indeed a way to run playgrounds on a particular PR. I'll add that to AspireUpdate docs.

**Comment by ipajen** [comment]
I am not sure I understand the purpose of the playground bransch.is the plan that releases to production are build from the playground bransch? I am used that there are dev bransch and when QA checked them in dev they will be merged to main bransch for production.

**Comment by asirota** [comment]
The playground branch is for people who want to quickly experiment with the plugin off docs.AspirePress.org 

And for causal testers. Like me.

**Comment by ipajen** [comment]
> The playground branch is for people who want to quickly experiment with the plugin off docs.AspirePress.org
> 
> And for causal testers. Like me.

I like the playground it self, but not sure why it needs a bransch for it, instead of using main/dev bransch.

**Comment by ipajen** [comment]
ahh its a place you want to play around to test changes for docs.AspirePress.org. Got it!

**Pull request merged**
