### PR TITLE
Updated German Translation

### PR DESCRIPTION
**Pull request by harikrishnanr994**
# Pull Request

## What changed?

Added missing German translations
Updated some translations

## Why did it change?

New translations required

## CERTIFICATION

By opening this pull request, I do agree to abide by
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time
of my contribution as proven by the
revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the
version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person
or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree
that this code may be licensed under any license deemed appropraite by AspirePress, including but not
limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my
rights or my copyright to this code.

### CODE REVIEW

**Comment by ipajen** [comment]
Could you use the latest https://github.com/aspirepress/AspireUpdate/blob/main/languages/AspireUpdate.pot there is a new string Unexpected Error: to be translated so it could be included in this PR. 🙏

**Review by asirota — APPROVED** [review]

**Review by namithj — APPROVED** [review]

**Review by ipajen — APPROVED** [review]
Not on latest .Po file but better to get the translated strings what's included.

**Comment by asirota** [comment]
Yeah I'll need to drop into VS Code to do it -- can't do a quick resolve here in the browser unfortunately. Be patient.

**Comment by asirota** [comment]
@harikrishnanr994 I have resolved the conflicts.

**Comment by asirota** [comment]
#153 will complete this PR.

**Pull request closed without merging**
