### PR TITLE
Improve I18N Issues Based on version 0.5

### PR DESCRIPTION
**Pull request by alexclassroom**
Including zh_TW language files.

# Pull Request

## What changed?

Fixed the current I18N issues

## Why did it change?

Making the plugin localizable means pushing it easier.

## Did you fix any specific issues?

(Please tag any specific issues here...)

## CERTIFICATION

By opening this pull request, I do agree to abide by
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time
of my contribution as proven by the
revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the
version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person
or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree
that this code may be licensed under any license deemed appropraite by AspirePress, including but not
limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my
rights or my copyright to this code.

### CODE REVIEW

**Comment by namithj** [comment]
@asirota How do we review translations?

**Comment by asirota** [comment]
You can change the language for WordPress  and the plugin should also change language assuming the language you switched to has been installed for the language. 

https://developer.wordpress.org/advanced-administration/before-install/in-your-language/

@alexclassroom can you confirm which language(s) you are providing here in the PR?

**Comment by asirota** [comment]
This is related to issue #75 which calls for language pack support.

**Comment by namithj** [comment]
It's Mandarin / Taiwanese.  How do we verify the translations.

**Comment by namithj** [comment]
Unless we know someone who knows the language the only option for a second eye is to use google translate to verify the translations.  The workflow should need a second eye so that we can be certain the translations are accurate.

**Comment by asirota** [comment]
Oh you mean the validity of the translation? The only way really to do it is with another native speaker? Or trust the translator implicitly. Beggars can't be choosers.

**Comment by namithj** [comment]
Yup, need a second eye on translations or we need to decide implicitly trust all sources right now as policy, for that we need a disclaimer.

**Comment by asirota** [comment]
Also while there is a need to have as many languages as possible, there is most definitely a priority of which languages are used right now online. English makes up 50% of the internet websites and then there is a long tail of languages with these making nearly the next 50%

image

From 
https://w3techs.com/technologies/overview/content_language

**Comment by alexclassroom** [comment]
You don't need to review/verify my translations because I am a qualified zh_TW community localizier.
Please view my bio [here](https://profiles.wordpress.org/alexclassroom/#content-translations).

**Review by namithj — APPROVED** [review]

**Review by asirota — APPROVED** [review]

**Comment by ipajen** [comment]
@alexclassroom  There is a new #polyglots slack, that you are if possible , welcome to join. https://aspirepress.org/slack/ 
Btw: there is some new strings to be translated.

**Pull request merged**
