### PR TITLE
Added License File

### PR DESCRIPTION
**Pull request by namithj**
Added License File

# Pull Request

## What changed?

Added License File

## Why did it change?

Added License File

## Did you fix any specific issues?

#68

## CERTIFICATION

By opening this pull request, I do agree to abide by
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time
of my contribution as proven by the
revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the
version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person
or entity, and I am not violating any license agreements or contracts I have with any person or entity. Finally, I agree
that this code may be licensed under any license deemed appropraite by AspirePress, including but not
limited to open source, closed source, proprietary or custom licenses, and that such license terms neither violate my
rights or my copyright to this code.

### CODE REVIEW

**Comment by asirota** [comment]
Just confirming is this the license you used

https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

**Comment by namithj** [comment]
I used the file that's autogenerated by GitHub when we select license as GPLv2.  It should be the same file.  Hold the PR, I will do a local diff and confirm as the file is too long to figure out if something is different manually.

**Comment by afragen** [comment]
There are also several places in the code that continue to reference GPLv3.

https://github.com/aspirepress/AspireUpdate/blob/46cd8f17bee61ccfa50a6bc5107a0d1d5ec8675c/aspire-update.php#L8

https://github.com/aspirepress/AspireUpdate/blob/46cd8f17bee61ccfa50a6bc5107a0d1d5ec8675c/aspire-update.php#L19

https://github.com/aspirepress/AspireUpdate/blob/46cd8f17bee61ccfa50a6bc5107a0d1d5ec8675c/composer.json#L5

https://github.com/aspirepress/AspireUpdate/blob/46cd8f17bee61ccfa50a6bc5107a0d1d5ec8675c/readme.txt#L9

Maybe a few more too.

**Comment by namithj** [comment]
This is good to go.  All references of GPL updated to GPLv2.  License file is also updated.

**Review by asirota — APPROVED** [review]
the coding standards checks are pretty specific -- good to start fixing these as we go forward, these are not major, but let's fix as we go if we can.

**Pull request merged**
